# File: .github/workflows/repo-sync.yml
name: sync-lxk
on:
  schedule:
    - cron: '1 */8 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://gitee.com/lxk0301/jd_scripts.git"
          source_branch: "master"
          destination_branch: "lxk"
          github_token: ${{ secrets.PAT }}
