# File: .github/workflows/repo-sync.yml
name: sync-lazy
on:
  schedule:
    - cron: '1 */4 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/jinboyigu/lazy_script.git"
          source_branch: "master"
          destination_branch: "lazy"
          github_token: ${{ secrets.PAT }}
      # 我自己同步到gitee使用，其他人可忽略
      - name: sync github -> gitee
        uses: wei/git-sync@v3
        with:
          source_repo: "wheatwee/789"
          source_branch: "lazy"
          destination_repo: "wheatwee/JDBK"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
