  
name: sync_secret
on:
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync_secret
env:
    DDFACTORY_SHARECODES: ${{ secrets.DDFACTORY_SHARECODES }}
    DREAM_FACTORY_SHARE_CODES: ${{ secrets.DREAM_FACTORY_SHARE_CODES }}
    FRUITSHARECODES: ${{ secrets.FRUITSHARECODES }}
    JDZZ_SHARECODES: ${{ secrets.JDZZ_SHARECODES }}
    JD_COOKIE: ${{ secrets.JD_COOKIE }}
    JOY_FEED_COUNT: ${{ secrets.JOY_FEED_COUNT }}
    JOY_HELP_FEED: ${{ secrets.JOY_HELP_FEED }}
    JXNC_SHARECODES: ${{ secrets.JXNC_SHARECODES }}
    PETSHARECODES: ${{ secrets.PETSHARECODES }}
    PLANT_BEAN_SHARECODES: ${{ secrets.PLANT_BEAN_SHARECODES }}
    PUSH_KEY: ${{ secrets.PUSH_KEY }}
    JDGLOBAL_SHARECODES: ${{ secrets.JDGLOBAL_SHARECODES }}
    JDJOY_SHARECODES: ${{ secrets.JDJOY_SHARECODES }}
    JDSXSY_SHARECODES: ${{ secrets.JDSXSY_SHARECODES }}
    JD_IMMORTAL_LATLON: ${{ secrets.JD_IMMORTAL_LATLON }}
    JSMOBILEFESTIVAL_SHARECODES: ${{ secrets.JSMOBILEFESTIVAL_SHARECODES }}
    UN_BIND_STOP_CARD: ${{ secrets.UN_BIND_STOP_CARD }}
    UN_SUBSCRIBES: ${{ secrets.UN_SUBSCRIBES }}

jobs:
  deploy:
    name: sync_secret
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.4.1
        with:
          secrets: |
            DDFACTORY_SHARECODES
            DREAM_FACTORY_SHARE_CODES
            FRUITSHARECODES
            JDZZ_SHARECODES
            JD_COOKIE
            JOY_FEED_COUNT
            JOY_HELP_FEED
            JXNC_SHARECODES
            PETSHARECODES
            PLANT_BEAN_SHARECODES
            PUSH_KEY
            JDGLOBAL_SHARECODES
            JDJOY_SHARECODES
            JDSXSY_SHARECODES
            JD_IMMORTAL_LATLON
            JSMOBILEFESTIVAL_SHARECODES
            UN_BIND_STOP_CARD
            UN_SUBSCRIBES

          repositories: |
            JDBACKUP.*$
          github_token: ${{ secrets.PAT }}
