# File: .github/workflows/repo-sync.yml
name: sync-163
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Secriy/CloudMusic-LevelUp.git"
          source_branch: "master"
          destination_branch: "163"
          github_token: ${{ secrets.PAT }}
  fix-cron:
    needs: repo-sync
    env:
      PAT: ${{ secrets.PAT }}      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 163
    - name: '运行 【修改cron】'
      shell: bash
      run: |
        sed -i 's/16/19/' .github/workflows/action.yml
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply fix-cron changes
        branch: 163
        file_pattern: .github/workflows/action.yml
  
  # 我自己同步到gitee使用，其他人可忽略
    - name: git-sync
      uses: wei/git-sync@v3
      with:
          source_repo: "wheatwee/789"
          source_branch: "163"
          destination_repo: "wheatwee/163"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
